name: Java CI with Maven

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 8.0.332+9
        cache: 'maven'
    - name: "[1/3] Compile and Test project"
      run: mvn test
    - name: "[2/3] Static Analysis"
      run: mvn package
    - name: Check if jacoco.xml exists
      run: |
        if [ -f target/site/jacoco/jacoco.xml ]; then
          echo " jacoco.xml found"
        else
          echo " jacoco.xml NOT FOUND"
          exit 1
        fi
    - name: "[3/3] Upload to Coveralls"
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: target/site/jacoco/jacoco.xml
        format: jacoco